### ISSUE TITLE
saliency values on mouseover

### ISSUE THREAD

**Issue by zia-hasan** [ServiceNow/azimuth#48]
**Describe the solution you'd like**
In the Utterance table under exploration, saliency values are not shown on mouseover unless the user clicks and opens the utterance in "utterance details" section.

**Comment by gabegma** [comment]
Hi Zia! The saliency values are not available in the utterance table by "design", because there is already another interaction implemented: when hovering on an utterance, the text "opens" in a larger box, to see the full utterance if it is long. So adding interaction with the saliency hovering is not straightforward to design and implement. That is why we disabled it in the utterance table. 

Can you tell me more about your use case? Why would you find it useful to directly see the saliency values in the utterance table? The colors are not sufficient?

**Comment by zia-hasan** [comment]
I see. I understand the Javascript challenge :). There wasn't a particular use case as such. It was just a little confusing to see it getting mentioned in the documentation but when it tried it on the utterance table (with yellow highlights), it seemed to not work and later realized that I have to click on the utterance to see their values. Perhaps you could clarify this in the documentation.

**Comment by gabegma** [comment]
Right, good point - we should clarify in the documentation!
